pull_request_rules:
  - name: p31 queue on label
    conditions:
      - base=main
      - label=p31-queue-me
    actions:
      queue:
        name: default

queue_rules:
  - name: default
    batch_size: 1
    queue_conditions:
      - base=main
    merge_conditions:
      - "#approved-reviews-by>=0"
    merge_method: merge
