queue_rules:
  - name: default
    batch_size: 1
    queue_conditions:
      - base=main
    merge_conditions:
      - "#approved-reviews-by>=0"
    merge_method: merge

pull_request_rules:
  - name: queue open prs
    conditions:
      - base=main
      - -closed
    actions:
      queue:
        name: default
